# Generated by Django 5.2.5 on 2025-08-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text="Identificador único para o texto (ex: 'hero_titulo'). Não altere.", max_length=100, unique=True)),
                ('valor', models.TextField(help_text='O texto que aparecerá no site.')),
            ],
            options={
                'verbose_name': 'Texto do Site',
                'verbose_name_plural': 'Textos do Site',
            },
        ),
        migrations.CreateModel(
            name='Diferencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(help_text="Nome do ícone do Lucide (ex: 'leaf', 'flask-conical', 'award').", max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Diferencial',
                'verbose_name_plural': 'Diferenciais',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pergunta Frequente (FAQ)',
                'verbose_name_plural': 'Perguntas Frequentes (FAQ)',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=300)),
                ('imagem', models.ImageField(upload_to='hero_slides/')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Use este número para ordenar os slides (0 aparece primeiro).')),
            ],
            options={
                'verbose_name': 'Slide da Home',
                'verbose_name_plural': 'Slides da Home',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Semente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(help_text='Ex: Brachiaria, Panicum', max_length=50)),
                ('nome_cientifico', models.CharField(max_length=100, verbose_name='Nome Científico')),
                ('imagem', models.ImageField(upload_to='sementes/')),
                ('paragrafo_descricao', models.TextField(verbose_name='Parágrafo de Descrição')),
                ('origem', models.CharField(blank=True, max_length=200)),
                ('forma_crescimento', models.CharField(blank=True, max_length=200, verbose_name='Forma de Crescimento')),
                ('altura', models.CharField(blank=True, max_length=100)),
                ('utilizacao', models.CharField(blank=True, max_length=100, verbose_name='Utilização')),
                ('digestibilidade', models.CharField(blank=True, max_length=100)),
                ('palatabilidade', models.CharField(blank=True, max_length=100)),
                ('tolerancia_seca', models.CharField(blank=True, max_length=100, verbose_name='Tolerância à Seca')),
                ('tolerancia_frio', models.CharField(blank=True, max_length=100, verbose_name='Tolerância ao Frio')),
                ('proteina_bruta', models.CharField(blank=True, max_length=100, verbose_name='Proteína Bruta')),
                ('producao_materia_seca', models.CharField(blank=True, max_length=100, verbose_name='Produção de Matéria Seca')),
                ('consorciacao', models.TextField(blank=True, verbose_name='Consorciação')),
                ('pragas', models.TextField(blank=True)),
                ('adubacao_formacao', models.TextField(blank=True, verbose_name='Adubação de Formação')),
            ],
            options={
                'verbose_name': 'Semente',
                'verbose_name_plural': 'Sementes',
                'ordering': ['nome'],
            },
        ),
    ]
