# Generated by Django 5.2.5 on 2025-08-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Logo principal que aparece no topo do site.', upload_to='config/')),
                ('imagem_fundo_dicas', models.ImageField(upload_to='config/', verbose_name="Imagem de Fundo da Seção 'Qualidade Garantida'")),
                ('mapa_url', models.URLField(help_text="Vá no Google Maps, clique em 'Compartilhar', depois 'Incorporar um mapa' e copie o link que está dentro do atributo 'src'.", max_length=500, verbose_name='URL de Incorporação do Google Maps')),
                ('endereco_rodovia', models.CharField(blank=True, max_length=255)),
                ('endereco_escritorio', models.CharField(blank=True, max_length=255)),
                ('telefone_fixo', models.CharField(blank=True, max_length=20)),
                ('telefone_celular', models.CharField(blank=True, help_text='Incluir o link do WhatsApp se desejar.', max_length=20)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Configurações Gerais do Site',
                'verbose_name_plural': 'Configurações Gerais do Site',
            },
        ),
        migrations.CreateModel(
            name='ItemNavegacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50)),
                ('link', models.CharField(help_text='Link da âncora (ex: #quemsomos) ou URL completa.', max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item de Navegação',
                'verbose_name_plural': 'Itens de Navegação',
                'ordering': ['ordem'],
            },
        ),
    ]
