# Generated by Django 5.2.5 on 2025-08-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracoesgerais_itemnavegacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoesgerais',
            name='sobre_nos_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='config/', verbose_name="Imagem da Seção 'Sobre Nós'"),
        ),
        migrations.AddField(
            model_name='configuracoesgerais',
            name='sobre_nos_p1',
            field=models.TextField(blank=True, verbose_name='Parágrafo 1'),
        ),
        migrations.AddField(
            model_name='configuracoesgerais',
            name='sobre_nos_p2',
            field=models.TextField(blank=True, verbose_name='Parágrafo 2'),
        ),
        migrations.AddField(
            model_name='configuracoesgerais',
            name='sobre_nos_p3',
            field=models.TextField(blank=True, verbose_name='Parágrafo 3 (destaque)'),
        ),
        migrations.AddField(
            model_name='configuracoesgerais',
            name='sobre_nos_titulo',
            field=models.CharField(blank=True, default='Sobre Nós', max_length=100),
        ),
        migrations.AddField(
            model_name='semente',
            name='aparece_na_comparacao',
            field=models.BooleanField(default=False, help_text="Marque esta opção para que a semente apareça na tabela 'Compare Nossas Soluções' na home. Recomenda-se marcar no máximo 4.", verbose_name='Aparece na tabela de comparação?'),
        ),
    ]
