# Generated by Django 5.2.5 on 2025-08-22 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracoesgerais_sobre_nos_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracoesgerais',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='configuracoesgerais',
            name='sobre_nos_imagem',
        ),
        migrations.AddField(
            model_name='configuracoesgerais',
            name='logo_principal',
            field=models.ImageField(blank=True, help_text='Logo para usar sobre o banner (geralmente na cor branca).', null=True, upload_to='config/', verbose_name='Logo Principal (Branco)'),
        ),
        migrations.AddField(
            model_name='configuracoesgerais',
            name='logo_secundario',
            field=models.ImageField(blank=True, help_text='Logo para usar quando o fundo do menu fica branco (geralmente na cor escura).', null=True, upload_to='config/', verbose_name='Logo Secundário (Escuro)'),
        ),
        migrations.CreateModel(
            name='ImagemSobreNos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='sobre_nos_slides/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_sobre_nos', to='core.configuracoesgerais')),
            ],
            options={
                'verbose_name': 'Imagem da Seção Sobre Nós',
                'verbose_name_plural': 'Imagens da Seção Sobre Nós',
                'ordering': ['ordem'],
            },
        ),
    ]
